version: '3.8'

services:
  clojure-app:
    container_name: backend-clojure
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - LEIN_ROOT=1

  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - clojure-app
    ports:
      - "80:80"
      - "443:80"

  prolog-client:
    build: ./prolog-bot
    environment:
      WEBSOCKET_SERVER_HOST: clojure-app
      WEBSOCKET_SERVER_PORT: 3000
    deploy:
      replicas: 3
    depends_on:
      - clojure-app
