name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    services:
      docker:
        image: docker:19.03.12

    env:
      CI_REGISTRY: ${{ vars.CI_REGISTRY }}
      CI_PROJECT_PATH: ${{ github.repository }}
      CI_COMMIT_SHORT_SHA: latest
      CI_PROJECT_DIR: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CI_REGISTRY }}
          username: json_key
          password: ${{ secrets.CI_REGISTRY_KEY }}

      - name: Set lowercase tags
        run: echo "TAGS=${CI_REGISTRY}/${CI_PROJECT_PATH,,}:${CI_COMMIT_SHORT_SHA}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CI_PROJECT_DIR }}
          push: true
          provenance: false
          tags: ${{ env.TAGS }}